// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-00SKMPYof1ymzssTiB51m6gtb8jpsy0',
    appId: '1:892528232776:web:1991017768a05a956e4b7d',
    messagingSenderId: '892528232776',
    projectId: 'chat-app-372ac',
    authDomain: 'chat-app-372ac.firebaseapp.com',
    storageBucket: 'chat-app-372ac.appspot.com',
    measurementId: 'G-M9BXF2WP34',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAEumfTaDMjXJIOzsKgsLM3u-1-YnRtAQ',
    appId: '1:892528232776:android:ead32f65cd7830376e4b7d',
    messagingSenderId: '892528232776',
    projectId: 'chat-app-372ac',
    storageBucket: 'chat-app-372ac.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9M7B-9BEsbJhxjTH_FZwZ8uB9P306FqU',
    appId: '1:892528232776:ios:3f5f200f884144506e4b7d',
    messagingSenderId: '892528232776',
    projectId: 'chat-app-372ac',
    storageBucket: 'chat-app-372ac.appspot.com',
    iosBundleId: 'com.example.chaaaaaaaaaaaaaat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9M7B-9BEsbJhxjTH_FZwZ8uB9P306FqU',
    appId: '1:892528232776:ios:3f5f200f884144506e4b7d',
    messagingSenderId: '892528232776',
    projectId: 'chat-app-372ac',
    storageBucket: 'chat-app-372ac.appspot.com',
    iosBundleId: 'com.example.chaaaaaaaaaaaaaat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-00SKMPYof1ymzssTiB51m6gtb8jpsy0',
    appId: '1:892528232776:web:23d0c28ddb9f55536e4b7d',
    messagingSenderId: '892528232776',
    projectId: 'chat-app-372ac',
    authDomain: 'chat-app-372ac.firebaseapp.com',
    storageBucket: 'chat-app-372ac.appspot.com',
    measurementId: 'G-KDZP99RYLD',
  );
}
